#!/usr/bin/env bash

source $(dirname $0)/sources/common.sh
depends sources/handle sources/about sources/generate sources/gpg sources/account sources/autocomplete sources/aliases sources/base

function cmd-help() {
    handle-help ${FUNCNAME} "$@"
    echo
    echo "USAGE:"
    echo "  topt <command> <options>"
    echo
    handle-help-commands ${FUNCNAME}
    echo 
}

function cmd-invalid() {
    local command="$1"
    local options=${@:2}
    echo "Invalid <command> ${command}"
    if [ ! -z "$options" ]; then
        echo "        <options> ${options}"
    fi
}

handle-command 'cmd' 'help' 'cmd-invalid' "$@"

